"use client";

import { useActionState, useEffect } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { saveBusinessProfile } from "@/features/settings/server/actions";
import {
  businessProfileSchema,
  type BusinessProfileInput,
} from "@/features/settings/schemas/business-profile";
import type {
  BusinessProfile,
  BusinessProfileActionState,
} from "@/features/settings/types/business-profile";

const initialState: BusinessProfileActionState = {};

type BusinessProfileFormProps = {
  profile: BusinessProfile | null;
};

/**
 * Create and update form for the authenticated user's single business profile.
 */
export function BusinessProfileForm({ profile }: BusinessProfileFormProps) {
  const [state, formAction, isPending] = useActionState(
    saveBusinessProfile,
    initialState,
  );
  const {
    formState: { errors },
    register,
    setError,
  } = useForm<BusinessProfileInput>({
    resolver: zodResolver(businessProfileSchema),
    defaultValues: {
      name: profile?.name ?? "",
      phone: profile?.phone ?? "",
      email: profile?.email ?? "",
      address: profile?.address ?? "",
      gstNumber: profile?.gstNumber ?? "",
      logoUrl: profile?.logoUrl ?? "",
    },
  });

  useEffect(() => {
    if (!state.fieldErrors) {
      return;
    }

    Object.entries(state.fieldErrors).forEach(([name, messages]) => {
      const message = messages?.[0];

      if (message) {
        setError(name as keyof BusinessProfileInput, { message });
      }
    });
  }, [setError, state.fieldErrors]);

  return (
    <Card className="max-w-3xl">
      <CardHeader>
        <CardTitle>Business profile</CardTitle>
        <CardDescription>
          These details will appear on invoices generated by BillFlow.
        </CardDescription>
      </CardHeader>
      <form action={formAction}>
        <CardContent>
          <FieldGroup>
            <Field data-invalid={Boolean(errors.name)}>
              <FieldLabel htmlFor="business-name">Business name</FieldLabel>
              <Input
                id="business-name"
                placeholder="Acme Private Limited"
                {...register("name")}
              />
              <FieldError errors={[errors.name]} />
            </Field>
            <div className="grid gap-7 md:grid-cols-2">
              <Field data-invalid={Boolean(errors.phone)}>
                <FieldLabel htmlFor="business-phone">Phone</FieldLabel>
                <Input
                  id="business-phone"
                  placeholder="+91 98765 43210"
                  {...register("phone")}
                />
                <FieldError errors={[errors.phone]} />
              </Field>
              <Field data-invalid={Boolean(errors.email)}>
                <FieldLabel htmlFor="business-email">Email</FieldLabel>
                <Input
                  id="business-email"
                  type="email"
                  placeholder="billing@example.com"
                  {...register("email")}
                />
                <FieldError errors={[errors.email]} />
              </Field>
            </div>
            <Field data-invalid={Boolean(errors.address)}>
              <FieldLabel htmlFor="business-address">Address</FieldLabel>
              <Textarea
                id="business-address"
                placeholder="Registered business address"
                rows={4}
                {...register("address")}
              />
              <FieldError errors={[errors.address]} />
            </Field>
            <div className="grid gap-7 md:grid-cols-2">
              <Field data-invalid={Boolean(errors.gstNumber)}>
                <FieldLabel htmlFor="business-gst-number">GST number</FieldLabel>
                <Input
                  id="business-gst-number"
                  placeholder="GST registration number"
                  {...register("gstNumber")}
                />
                <FieldError errors={[errors.gstNumber]} />
              </Field>
              <Field data-invalid={Boolean(errors.logoUrl)}>
                <FieldLabel htmlFor="business-logo-url">Logo URL</FieldLabel>
                <Input
                  id="business-logo-url"
                  type="url"
                  placeholder="https://example.com/logo.png"
                  {...register("logoUrl")}
                />
                <FieldDescription>
                  Use a public image URL for your invoice header.
                </FieldDescription>
                <FieldError errors={[errors.logoUrl]} />
              </Field>
            </div>
          </FieldGroup>
          {state.error ? (
            <p className="mt-6 text-sm text-destructive" role="alert">
              {state.error}
            </p>
          ) : null}
          {state.success ? (
            <p className="mt-6 text-sm text-muted-foreground" role="status">
              {state.success}
            </p>
          ) : null}
        </CardContent>
        <CardFooter className="justify-end">
          <Button type="submit" disabled={isPending}>
            {isPending ? "Saving..." : profile ? "Update profile" : "Create profile"}
          </Button>
        </CardFooter>
      </form>
    </Card>
  );
}
